version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "taskdefinition.json"
        LoadBalancerInfo:
          ContainerName: "javatechie-registry"
          ContainerPort: 8080
Hooks:
  BeforeInstall:
    - location: "scripts/setup.sh"
      timeout: 60
      runas: "root"




