version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "taskdefinition.json"  # This should be a path to a JSON file generated during your build process
        LoadBalancerInfo:
          ContainerName: "javatechie-registry"
          ContainerPort: 8080



